import './App.css';
import {useState} from "react";

var headingText = "Poke-Pedia";
var descMsg1 = "This is Poke-Pedia.";
var descMsg2 = "Click on a pokemon to get to know it's type.";
const pokeDb = {
  "Abomasnow" : "Grass	Ice	" ,
  "Abra" : "Psychic	" ,
  "Absol" :	"Dark	" ,
  "Accelgor" : "Bug	" ,
  "Aegislash" : "Steel	Ghost" ,
  "Aerodactyl" : "Rock	Flying" ,
  "Aggron" :	"Steel	Rock	" ,
  "Aipom" : "Normal	" ,
  "Alakazam" : "Psychic	" ,
  "Alcremie" : "Fairy	" ,
  "Alomomola" : "Water	" ,
  "Altaria" :	"Dragon	Flying	" ,
  "Amaura" : "Rock	Ice" ,
  "Ambipom" : "Normal		" ,
  "Amoonguss" : "Grass	Poison" ,
  "Ampharos" : "Electric	" ,
  "Anorith" :	"Rock	Bug" ,
  "Appletun" : "Grass	Dragon" ,
  "Applin" : "Grass	Dragon" ,
  "Araquanid" : "Water	Bug" ,
  "Arbok" : "Poison	" ,
  "Arcanine" : "Fire	" ,
  "Arceus" : "Normal		" ,
  "Archen" : "Rock	Flying" ,
  "Archeops" : "Rock	Flying" ,
  "Arctovish" : "Water	Ice" ,
  "Arctozolt" : "Electric	Ice" ,
  "Ariados" : "Bug	Poison" ,
  "Armaldo" :	"Rock	Bug" ,
  "Aromatisse" : "Fairy	" ,
  "Aron" :	"Steel	Rock	" ,
  "Arrokuda" : "Water	" ,
  "Articuno" : "Ice	Flying" ,
  "Audino" : "Normal	" ,
  "Aurorus" : "Rock	Ice" ,
  "Avalugg" : "Ice	" ,
  "Axew" : "Dragon	" ,
  "Azelf" : "Psychic		" ,
  "Azumarill" : "Water	Fairy" ,
  "Azurill" :	"Normal	Fairy" ,
  "Bagon" :	"Dragon	" ,
  "Baltoy" :	"Ground	Psychic" ,
  "Banette" :	"Ghost	" ,
  "Barbaracle" : "Rock	Water" ,
  "Barboach" :	"Water	Ground	" ,
  "Barraskewda" : "Water	" ,
  "Basculegion" : "water	Ghost" ,
  "Basculin" : "Water	" ,
  "Bastiodon" : "Rock	Steel	" ,
  "Bayleef" : "Grass	" ,
  "Beartic" : "Ice	" ,
  "Beautifly" :	"Bug	Flying	" ,
  "Beedrill" : "Bug	Poison" ,
  "Beheeyem" : "Psychic	" ,
  "Beldum" :	"Steel	Psychic" ,
  "Bellossom" : "Grass	" ,
  "Bellsprout" : "Grass	Poison" ,
  "Bergmite" : "Ice	" ,
  "Bewear" : "Normal	Fighting" ,
  "Bibarel" : "Normal	Water	" ,
  "Bidoof" : "Normal		" ,
  "Binacle" : "Rock	Water" ,
  "Bisharp" : "Dark	Steel" ,
  "Blacephalon" : "Fire	Ghost" ,
  "Blastoise" : "Water	" ,
  "Blaziken" :	"Fire	Fighting	" ,
  "Blipbug" : "Bug	" ,
  "Blissey" : "Normal	" ,
  "Blitzle" : "Electric	" ,
  "Boldore" : "Rock	" ,
  "Boltund" : "Electric	" ,
  "Bonsly" : "Rock		" ,
  "Bouffalant" : "Normal	" ,
  "Bounsweet" : "Grass	" ,
  "Braixen" : "Fire	" ,
  "Braviary" : "Normal	Flying" ,
  "Breloom" :	"Grass	Fighting	" ,
  "Brionne" : "Water	" ,
  "Bronzong" : "Steel	Psychic	" ,
  "Bronzor" : "Steel	Psychic	" ,
  "Bruxish" : "Water	Psychic" ,
  "Budew" : "Grass	Poison	" ,
  "Buizel" : "Water		" ,
  "Bulbasaur" : "Grass Poison" ,
  "Buneary" : "Normal		" ,
  "Bunnelby" : "Normal	" ,
  "Burmy" : "Bug		" ,
  "Butterfree" : "Bug	Flying" ,
  "Buzzwole" : "Bug	Fighting" ,
  "Cacnea" :	"Grass		" ,
  "Cacturne" :	"Grass	Dark	" ,
  "Calyrex" : "Psychic	Grass" ,
  "Camerupt" :	"Fire	Ground	" ,
  "Carbink" : "Rock	Fairy" ,
  "Carkol" : "Rock	Fire" ,
  "Carnivine" : "Grass		" ,
  "Carracosta" : "Water	Rock" ,
  "Carvanha" :	"Water	Dark	" ,
  "Cascoon" :	"Bug		" ,
  "Castform" :	"Normal	" ,
  "Caterpie" : "Bug	" ,
  "Celebi" : "Psychic	Grass" ,
  "Celesteela" : "Steel	Flying" ,
  "Centiskorch" : "Fire	Bug" ,
  "Chandelure" : "Ghost	Fire" ,
  "Chansey" : "Normal	" ,
  "Charizard" : "Fire	Flying" ,
  "Charjabug" : "Bug	Electric" ,
  "Charmander" : "Fire	" ,
  "Charmeleon" : "Fire	" ,
  "Chatot" : "Normal	Flying	" ,
  "Cherrim" : "Grass		" ,
  "Cherubi" : "Grass		" ,
  "Chesnaught" : "Grass	Fighting" ,
  "Chespin" : "Grass	" ,
  "Chewtle" : "Water	" ,
  "Chikorita" : "Grass	" ,
  "Chimchar" : "Fire		" ,
  "Chimecho" :	"Psychic	" ,
  "Chinchou" : "Water	Electric" ,
  "Chingling" : "Psychic		" ,
  "Cinccino" : "Normal	" ,
  "Cinderace" : "Fire	" ,
  "Clamperl" :	"Water	" ,
  "Clauncher" : "Water	" ,
  "Clawitzer" : "Water	" ,
  "Claydol" :	"Ground	Psychic" ,
  "Clefable" : "Fairy" ,
  "Clefairy" : "Fairy" ,
  "Cleffa" : "Fairy" ,
  "Clobbopus" : "Fighting	" ,
  "Cloyster" : "Water	Ice" ,
  "Coalossal" : "Rock	Fire" ,
  "Cobalion" : "Steel	Fighting" ,
  "Cofagrigus" : "Ghost	" ,
  "Combee" : "Bug	Flying	" ,
  "Combusken" :	"Fire	Fighting	" ,
  "Comfey" : "Fairy	" ,
  "Conkeldurr" : "Fighting	" ,
  "Copperajah" : "Steel	" ,
  "Corphish" :	"Water		" ,
  "Corsola" : "Water	Rock" ,
  "Corviknight" : "Flying	Steel" ,
  "Corvisquire" : "Flying	" ,
  "Cosmoem" : "Psychic	" ,
  "Cosmog" : "Psychic	" ,
  "Cottonee" : "Grass	Fairy" ,
  "Crabominable" : "Fighting	Ice" ,
  "Crabrawler" : "Fighting	" ,
  "Cradily" :	"Rock	Grass" ,
  "Cramorant" : "Flying	Water" ,
  "Cranidos" : "Rock		" ,
  "Crawdaunt" :	"Water	Dark" ,
  "Cresselia" : "Psychic		" ,
  "Croagunk" : "Poison	Fighting	" ,
  "Crobat" : "Poison	Flying" ,
  "Croconaw" : "Water	" ,
  "Crustle" : "Bug	Rock" ,
  "Cryogonal" : "Ice	" ,
  "Cubchoo" : "Ice	" ,
  "Cubone" : "Ground	" ,
  "Cufant" : "Steel	" ,
  "Cursola" : "Ghost	" ,
  "Cutiefly" : "Bug	Fairy" ,
  "Cyndaquil" : "Fire	" ,
  "Darkrai" : "Dark		" ,
  "Darmanitan" : "Fire	" ,
  "Dartrix" : "Grass	Flying" ,
  "Darumaka" : "Fire	" ,
  "Decidueye" : "Grass	Ghost" ,
  "Dedenne" : "Electric	Fairy" ,
  "Deerling" : "Normal	Grass" ,
  "Deino" : "Dark	Dragon" ,
  "Delcatty" :	"Normal		" ,
  "Delibird" : "Ice	Flying" ,
  "Delphox" : "Fire	Psychic" ,
  "Deoxys" :	"Psychic	" ,
  "Dewgong" : "Water	Ice" ,
  "Dewott" : "Water	" ,
  "Dewpider" : "Water	Bug" ,
  "Dhelmise" : "Ghost	Grass" ,
  "Dialga" : "Steel	Dragon	" ,
  "Diancie" : "Rock	Fairy" ,
  "Diggersby" : "Normal	Ground" ,
  "Diglett" : "Ground	" ,
  "Ditto" : "Normal	" ,
  "Dodrio" : "Normal	Flying" ,
  "Doduo" : "Normal	Flying" ,
  "Donphan" : "Ground	" ,
  "Dottler" : "Bug	Psychic" ,
  "Doublade" : "Steel	Ghost" ,
  "Dracovish" : "Water	Dragon" ,
  "Dracozolt" : "Electric	Dragon" ,
  "Dragalge" : "Poison	Dragon" ,
  "Dragapult" : "Dragon	Ghost" ,
  "Dragonair" : "Dragon	" ,
  "Dragonite" : "Dragon	Flying" ,
  "Drakloak" : "Dragon	Ghost" ,
  "Drampa" : "Normal	Dragon" ,
  "Drapion" : "Poison	Dark	" ,
  "Dratini" : "Dragon	" ,
  "Drednaw" : "Water	Rock" ,
  "Dreepy" : "Dragon	Ghost" ,
  "Drifblim" : "Ghost	Flying	" ,
  "Drifloon" : "Ghost	Flying	" ,
  "Drilbur" : "Ground	" ,
  "Drizzile" : "Water	" ,
  "Drowzee" : "Psychic	" ,
  "Druddigon" : "Dragon	" ,
  "Dubwool" : "Normal	" ,
  "Ducklett" : "Water	Flying" ,
  "Dugtrio" : "Ground	" ,
  "Dunsparce" : "Normal	" ,
  "Duosion" : "Psychic	" ,
  "Duraludon" : "Steel	Dragon" ,
  "Durant" : "Bug	Steel" ,
  "Dusclops" :	"Ghost	" ,
  "Dusknoir" : "Ghost		" ,
  "Duskull" :	"Ghost	" ,
  "Dustox" :	"Bug	Poison	" ,
  "Dwebble" : "Bug	Rock" ,
  "Eelektrik" : "Electric	" ,
  "Eelektross" : "Electric	" ,
  "Eevee" : "Normal	" ,
  "Eiscue" : "Ice	" ,
  "Ekans" : "Poison	" ,
  "Eldegoss" : "Grass	" ,
  "Electabuzz" : "Electric	" ,
  "Electivire" : "Electric		" ,
  "Electrike" :	"Electric		" ,
  "Electrode" : "Electric	" ,
  "Elekid" : "Electric	" ,
  "Elgyem" : "Psychic	" ,
  "Emboar" : "Fire	Fighting" ,
  "Emolga" : "Electric	Flying" ,
  "Empoleon" : "Water	Steel	" ,
  "Entei" : "Fire	" ,
  "Escavalier" : "Bug	Steel" ,
  "Espeon" : "Psychic	" ,
  "Espurr" : "Psychic	" ,
  "Eternatus" : "Poison	Dragon" ,
  "Excadrill" : "Ground	Steel" ,
  "Exeggcute" : "Grass	Psychic" ,
  "Exeggutor" : "Grass	Psychic" ,
  "Exploud" :	"Normal		" ,
  "Falinks" : "Fighting	" ,
  "Farfetch'd" : "Normal	Flying" ,
  "Fearow" : "Normal	Flying" ,
  "Feebas" :	"Water	" ,
  "Fennekin" : "Fire	" ,
  "Feraligatr" : "Water	" ,
  "Ferroseed" : "Grass	Steel" ,
  "Ferrothorn" : "Grass	Steel" ,
  "Finneon" : "Water		" ,
  "Flaaffy" : "Electric	" ,
  "Flabébé" : "Fairy	" ,
  "Flapple" : "Grass	Dragon" ,
  "Flareon" : "Fire	" ,
  "Fletchinder" : "Fire	Flying" ,
  "Fletchling" : "Normal	Flying" ,
  "Floatzel" : "Water		" ,
  "Floette" : "Fairy	" ,
  "Florges" : "Fairy	" ,
  "Flygon" :	"Ground	Dragon	" ,
  "Fomantis" : "Grass	" ,
  "Foongus" : "Grass	Poison" ,
  "Forretress" : "Bug	Steel" ,
  "Fraxure" : "Dragon	" ,
  "Frillish" : "Water	Ghost" ,
  "Froakie" : "Water	" ,
  "Frogadier" : "Water	" ,
  "Froslass" : "Ice	Ghost	" ,
  "Frosmoth" : "Ice	Bug" ,
  "Furfrou" : "Normal	" ,
  "Furret" : "Normal	" ,
  "Gabite" : "Dragon	Ground	" ,
  "Gallade" : "Psychic	Fighting	" ,
  "Galvantula" : "Bug	Electric" ,
  "Garbodor" : "Poison	" ,
  "Garchomp" : "Dragon	Ground	" ,
  "Gardevoir" :	"Psychic	Fairy" ,
  "Gastly" : "Ghost	Poison" ,
  "Gastrodon" : "Water	Ground	" ,
  "Genesect" : "Bug	Steel" ,
  "Gengar" : "Ghost	Poison" ,
  "Geodude" : "Rock	Ground" ,
  "Gible" : "Dragon	Ground	" ,
  "Gigalith" : "Rock	" ,
  "Girafarig" : "Normal	Psychic" ,
  "Giratina" : "Ghost	Dragon	" ,
  "Glaceon" : "Ice		" ,
  "Glalie" :	"Ice	" ,
  "Glameow" : "Normal		" ,
  "Glastrier" : "Ice	" ,
  "Gligar" : "Ground	Flying" ,
  "Gliscor" : "Ground	Flying	" ,
  "Gloom" : "Grass	Poison" ,
  "Gogoat" : "Grass	" ,
  "Golbat" : "Poison	Flying" ,
  "Goldeen" : "Water	" ,
  "Golduck" : "Water	" ,
  "Golem" : "Rock	Ground" ,
  "Golett" : "Ground	Ghost" ,
  "Golisopod" : "Bug	Water" ,
  "Golurk" : "Ground	Ghost" ,
  "Goodra" : "Dragon	" ,
  "Goomy" : "Dragon	" ,
  "Gorebyss" :	"Water	" ,
  "Gossifleur" : "Grass	" ,
  "Gothita" : "Psychic	" ,
  "Gothitelle" : "Psychic	" ,
  "Gothorita" : "Psychic	" ,
  "Gourgeist" : "Ghost	Grass" ,
  "Granbull" : "Fairy" ,
  "Grapploct" : "Fighting	" ,
  "Graveler" : "Rock	Ground" ,
  "Greedent" : "Normal	" ,
  "Greninja" : "Water	Dark" ,
  "Grimer" : "Poison	" ,
  "Grimmsnarl" : "Dark	Fairy" ,
  "Grookey" : "Grass	" ,
  "Grotle" : "Grass		" ,
  "Groudon" :	"Ground	" ,
  "Grovyle" :	"Grass" ,
  "Growlithe" : "Fire	" ,
  "Grubbin" : "Bug	" ,
  "Grumpig" :	"Psychic		" ,
  "Gulpin" :	"Poison		" ,
  "Gumshoos" : "Normal	" ,
  "Gurdurr" : "Fighting	" ,
  "Guzzlord" : "Dark	Dragon" ,
  "Gyarados" : "Water	Flying" ,
  "Hakamo-o" : 	"Dragon	Fighting" ,
  "Happiny" : "Normal		" ,
  "Hariyama" :	"Fighting		" ,
  "Hatenna" : "Psychic	" ,
  "Hatterene" : "Psychic	Fairy" ,
  "Hattrem" : "Psychic	" ,
  "Haunter" : "Ghost	Poison" ,
  "Hawlucha" : "Fighting	Flying" ,
  "Haxorus" : "Dragon	" ,
  "Heatmor" : "Fire	" ,
  "Heatran" : "Fire	Steel	" ,
  "Heliolisk" : "Electric	Normal" ,
  "Helioptile" : "Electric	Normal" ,
  "Heracross" : "Bug	Fighting" ,
  "Herdier" : "Normal	" ,
  "Hippopotas" : "Ground		" ,
  "Hippowdon" : "Ground		" ,
  "Hitmonchan" : "Fighting	" ,
  "Hitmonlee" : "Fighting	" ,
  "Hitmontop" : "Fighting	" ,
  "Ho-h" : "Fire	Flying" ,
  "Honchkrow" : "Dark	Flying	" ,
  "Honedge" : "Steel	Ghost" ,
  "Hoopa" : "Psychic	Ghost" ,
  "Hoothoot" : "Normal	Flying" ,
  "Hoppip" : "Grass	Flying" ,
  "Horsea" : "Water	" ,
  "Houndoom" : "Dark	Fire" ,
  "Houndour" : "Dark	Fire" ,
  "Huntail" :	"Water	" ,
  "Hydreigon" : "Dark	Dragon" ,
  "Hypno" : "Psychic	" ,
  "Igglybuff" : "Normal	Fairy" ,
  "Illumise" :	"Bug		" ,
  "Impidimp" : "Dark	Fairy" ,
  "Incineroar" : "Fire	Dark" ,
  "Indeedee" : "Psychic	Normal" ,
  "Infernape" : "Fire	Fighting	" ,
  "Inkay" : "Dark	Psychic" ,
  "Inteleon" : "Water	" ,
  "Ivysaur" : "Grass	Poison" ,
  "Jangmo-o" : 	"Dragon	" ,
  "Jellicent" : "Water	Ghost" ,
  "Jigglypuff" : "Normal	Fairy" ,
  "Jirachi" :	"Steel	Psychic" ,
  "Jolteon" : "Electric	" ,
  "Joltik" : "Bug	Electric" ,
  "Jumpluff" : "Grass	Flying" ,
  "Jynx" : "Ice	Psychic" ,
  "Kabuto" : "Rock	Water" ,
  "Kabutops" : "Rock	Water" ,
  "Kadabra" : "Psychic	" ,
  "Kakuna" : "Bug	Poison" ,
  "Kangaskhan" : "Normal	" ,
  "Karrablast" : "Bug	" ,
  "Kartana" : "Grass	Steel" ,
  "Kecleon" :	"Normal	" ,
  "Keldeo" : "Water	Fighting" ,
  "Kingdra" : "Water	Dragon" ,
  "Kingler" : "Water	" ,
  "Kirlia" :	"Psychic	Fairy" ,
  "Klang" : "Steel	" ,
  "Klefki" : "Steel	Fairy" ,
  "Klink" : "Steel	" ,
  "Klinklang" : "Steel	" ,
  "Koffing" : "Poison	" ,
  "Komala" : "Normal	" ,
  "Kommo-o" : 	"Dragon	Fighting" ,
  "Krabby" : "Water	" ,
  "Kricketot" : "Bug		" ,
  "Kricketune" : "Bug		" ,
  "Krokorok" : "Ground	Dark" ,
  "Krookodile" : "Ground	Dark" ,
  "Kubfu" : "Fighting	" ,
  "Kyogre" :	"Water	" ,
  "Kyurem" : "Dragon	Ice" ,
  "Lairon" :	"Steel	Rock	" ,
  "Lampent" : "Ghost	Fire" ,
  "Landorus" : "Ground	Flying" ,
  "Lanturn" : "Water	Electric" ,
  "Lapras" : "Water	Ice" ,
  "Larvesta" : "Bug	Fire" ,
  "Larvitar" : "Rock	Ground" ,
  "Latias" :	"Dragon	Psychic" ,
  "Latios" :	"Dragon	Psychic" ,
  "Leafeon" : "Grass		" ,
  "Leavanny" : "Bug	Grass" ,
  "Ledian" : "Bug	Flying" ,
  "Ledyba" : "Bug	Flying" ,
  "Lickilicky" : "Normal		" ,
  "Lickitung" : "Normal	" ,
  "Liepard" : "Dark	" ,
  "Lileep" :	"Rock	Grass" ,
  "Lilligant" : "Grass	" ,
  "Lillipup" : "Normal	" ,
  "Linoone" :	"Normal		" ,
  "Litleo" : "Fire	Normal" ,
  "Litten" : "Fire	" ,
  "Litwick" : "Ghost	Fire" ,
  "Lombre" :	"Water	Grass	" ,
  "Lopunny" : "Normal		" ,
  "Lotad" :	"Water	Grass	" ,
  "Loudred" :	"Normal		" ,
  "Lucario" : "Fighting	Steel	" ,
  "Ludicolo" :	"Water	Grass	" ,
  "Lugia" : "Psychic	Flying" ,
  "Lumineon" : "Water		" ,
  "Lunala" : "Psychic	Ghost" ,
  "Lunatone" :	"Rock	Psychic	" ,
  "Lurantis" : "Grass	" ,
  "Luvdisc" :	"Water	" ,
  "Luxio" : "Electric		" ,
  "Luxray" : "Electric		" ,
  "Lycanroc" : "Rock	" ,
  "Machamp" : "Fighting	" ,
  "Machoke" : "Fighting	" ,
  "Machop" : "Fighting	" ,
  "Magby" : "Fire	" ,
  "Magcargo" : "Fire	Rock" ,
  "Magearna" : "Steel	Fairy" ,
  "Magikarp" : "Water	" ,
  "Magmar" : "Fire	" ,
  "Magmortar" : "Fire		" ,
  "Magnemite" : "Electric	Steel" ,
  "Magneton" : "Electric	Steel" ,
  "Magnezone" : "Electric	Steel	" ,
  "Makuhita" :	"Fighting		" ,
  "Malamar" : "Dark	Psychic" ,
  "Mamoswine" : "Ice	Ground	" ,
  "Manaphy" : "Water		" ,
  "Mandibuzz" : "Dark	Flying" ,
  "Manectric" :	"Electric		" ,
  "Mankey" : "Fighting	" ,
  "Mantine" : "Water	Flying" ,
  "Mantyke" : "Water	Flying	" ,
  "Maractus" : "Grass	" ,
  "Mareanie" : "Poison	Water" ,
  "Mareep" : "Electric	" ,
  "Marill" : "Water	Fairy" ,
  "Marowak" : "Ground	" ,
  "Marshadow" : "Fighting	Ghost" ,
  "Marshtomp" :	"Water	Ground	" ,
  "Masquerain" :	"Bug	Flying	" ,
  "Mawile" :	"Steel	Fairy" ,
  "Medicham" :	"Fighting	Psychic	" ,
  "Meditite" :	"Fighting	Psychic	" ,
  "Meganium" : "Grass	" ,
  "Melmetal" : "Steel	 " ,
  "Meloetta" : "Normal	Psychic" ,
  "Meltan" : "Steel	" ,
  "Meowstic" : "Psychic	" ,
  "Meowth" : "Normal	" ,
  "Mesprit" : "Psychic		" ,
  "Metagross" :	"Steel	Psychic" ,
  "Metang" :	"Steel	Psychic" ,
  "Metapod" : "Bug	" ,
  "Mew" : "Psychic	" ,
  "Mewtwo" : "Psychic	" ,
  "Mienfoo" : "Fighting	" ,
  "Mienshao" : "Fighting	" ,
  "Mightyena" :	"Dark		" ,
  "Milcery" : "Fairy	" ,
  "Milotic" :	"Water	" ,
  "Miltank" : "Normal	" ,
  "Mime Jr." : "Psychic	Fairy" ,
  "Mimikyu" : "Ghost	Fairy" ,
  "Minccino" : "Normal	" ,
  "Minior" : "Rock	Flying" ,
  "Minun" :	"Electric		" ,
  "Misdreavus" : "Ghost	" ,
  "Mismagius" : "Ghost		" ,
  "Moltres" : "Fire	Flying" ,
  "Monferno" : "Fire	Fighting	" ,
  "Morelull" : "Grass	Fairy" ,
  "Morgrem" : "Dark	Fairy" ,
  "Morpeko" : "Electric	Dark" ,
  "Mothim" : "Bug	Flying	" ,
  "Mr. Mime":	"Psychic	Fairy" ,
  "Mr. Rime":	"Ice	Psychic" ,
  "Mudbray" : "Ground	" ,
  "Mudkip" :	"Water		" ,
  "Mudsdale" : "Ground	" ,
  "Muk" : "Poison	" ,
  "Munchlax" : "Normal		" ,
  "Munna" : "Psychic	" ,
  "Murkrow" : "Dark	Flying" ,
  "Musharna" : "Psychic	" ,
  "Naganadel" : "Poison	Dragon" ,
  "Natu" : "Psychic	Flying" ,
  "Necrozma" : "Psychic	" ,
  "Nickit" : "Dark	" ,
  "Nidoking" : "Poison	Ground" ,
  "Nidoqueen" : "Poison	Ground" ,
  "Nidoran♀" : "Poison	" ,
  "Nidoran♂" : "Poison	" ,
  "Nidorina" : "Poison	" ,
  "Nidorino" : "Poison	" ,
  "Nihilego" : "Rock	Poison" ,
  "Nincada" :	"Bug	Ground	" ,
  "Ninetales" : "Fire	" ,
  "Ninjask" :	"Bug	Flying	" ,
  "Noctowl" : "Normal	Flying" ,
  "Noibat" : "Flying	Dragon" ,
  "Noivern" : "Flying	Dragon" ,
  "Nosepass" :	"Rock		" ,
  "Numel" :	"Fire	Ground	" ,
  "Nuzleaf" :	"Grass	Dark	" ,
  "Obstagoon" : "Dark	Normal" ,
  "Octillery" : "Water	" ,
  "Oddish" : "Grass	Poison" ,
  "Omanyte" : "Rock	Water" ,
  "Omastar" : "Rock	Water" ,
  "Onix" : "Rock	Ground" ,
  "Oranguru" : "Normal	Psychic" ,
  "Orbeetle" : "Bug	Psychic" ,
  "Oricorio" : "Fire" ,
  "Oshawott" : "Water	" ,
  "Pachirisu" : "Electric		" ,
  "Palkia" : "Water	Dragon	" ,
  "Palossand" : "Ghost	Ground" ,
  "Palpitoad" : "Water	Ground" ,
  "Pancham" : "Fighting	" ,
  "Pangoro" : "Fighting	Dark" ,
  "Panpour" : "Water	" ,
  "Pansage" : "Grass	" ,
  "Pansear" : "Fire	" ,
  "Paras" : "Bug	Grass" ,
  "Parasect" : "Bug	Grass" ,
  "Passimian" : "Fighting	" ,
  "Patrat" : "Normal	" ,
  "Pawniard" : "Dark	Steel" ,
  "Pelipper" :	"Water	Flying	" ,
  "Perrserker" : "Steel	" ,
  "Persian" : "Normal	" ,
  "Petilil" : "Grass	" ,
  "Phanpy" : "Ground	" ,
  "Phantump" : "Ghost	Grass" ,
  "Pheromosa" : "Bug	Fighting" ,
  "Phione" : "Water		" ,
  "Pichu" : "Electric	" ,
  "Pidgeot" : "Normal	Flying" ,
  "Pidgeotto" : "Normal	Flying" ,
  "Pidgey" : "Normal	Flying" ,
  "Pidove" : "Normal	Flying" ,
  "Pignite" : "Fire	Fighting" ,
  "Pikachu" : "Electric	" ,
  "Pikipek" : "Normal	Flying" ,
  "Piloswine" : "Ice	Ground" ,
  "Pincurchin" : "Electric" ,
  "Pineco" : "Bug	" ,
  "Pinsir" : "Bug	" ,
  "Piplup" : "Water		" ,
  "Plusle" :	"Electric		" ,
  "Poipole" : "Poison	" ,
  "Politoed" : "Water	" ,
  "Poliwag" : "Water	" ,
  "Poliwhirl" : "Water	" ,
  "Poliwrath" : "Water	Fighting" ,
  "Polteageist" : "Ghost	" ,
  "Ponyta" : "Fire	" ,
  "Poochyena" :	"Dark		" ,
  "Popplio" : "Water	" ,
  "Porygon" : "	Normal		" ,
  "Porygon2" : "Normal	" ,
  "Primarina" : "Water	Fairy" ,
  "Primeape" : "Fighting	" ,
  "Prinplup" : "Water		" ,
  "Probopass" : "Rock	Steel	" ,
  "Psyduck" : "Water	" ,
  "Pumpkaboo" : "Ghost	Grass" ,
  "Pupitar" : "Rock	Ground" ,
  "Purrloin" : "Dark	" ,
  "Purugly" : "Normal		" ,
  "Pyroar" : "Fire	Normal" ,
  "Pyukumuku" : "Water	" ,
  "Quagsire" : "Water	Ground" ,
  "Quilava" : "Fire	" ,
  "Quilladin" : "Grass	" ,
  "Qwilfish" : "Water	Poison" ,
  "Raboot" : "Fire	" ,
  "Raichu" : "Electric	" ,
  "Raikou" : "Electric	" ,
  "Ralts" :	"Psychic	Fairy" ,
  "Rampardos" : "Rock		" ,
  "Rapidash" : "Fire	" ,
  "Raticate" : "Normal	" ,
  "Rattata" : "Normal	" ,
  "Rayquaza" :	"Dragon	Flying" ,
  "Regice" :	"Ice	" ,
  "Regidrago" : "Dragon	" ,
  "Regieleki" : "Electric	" ,
  "Regigigas" : "Normal		" ,
  "Regirock" :	"Rock	" ,
  "Registeel" :	"Steel	" ,
  "Relicanth" :	"Water	Rock" ,
  "Remoraid" : "Water	" ,
  "Reshiram" : "Dragon	Fire" ,
  "Reuniclus" : "Psychic	" ,
  "Rhydon" : "Ground	Rock" ,
  "Rhyhorn" : "Ground	Rock" ,
  "Rhyperior" : "Ground	Rock	" ,
  "Ribombee" : "Bug	Fairy" ,
  "Rillaboom" : "Grass	" ,
  "Riolu" : "Fighting		" ,
  "Rockruff" : "Rock	" ,
  "Roggenrola" : "Rock	" ,
  "Rolycoly" : "Rock	" ,
  "Rookidee" : "Flying	" ,
  "Roselia" :	"Grass	Poison	" ,
  "Roserade" : "Grass	Poison	" ,
  "Rotom" : "Electric	Ghost	" ,
  "Rowlet" : "Grass	Flying" ,
  "Rufflet" : "Normal	Flying" ,
  "Runerigus" : "Ground	Ghost" ,
  "Sableye" :	"Dark	Ghost	" ,
  "Salamence" :	"Dragon	Flying" ,
  "Salandit" : "Poison	Fire" ,
  "Salazzle" : "Poison	Fire" ,
  "Samurott" : "Water	" ,
  "Sandaconda" : "Ground	" ,
  "Sandile" : "Ground	Dark" ,
  "Sandshrew" : "Ground	" ,
  "Sandslash" : "Ground	" ,
  "Sandygast" : "Ghost	Ground" ,
  "Sawk" : "Fighting	" ,
  "Sawsbuck" : "Normal	Grass" ,
  "Scatterbug" : "Bug	" ,
  "Sceptile" :	"Grass		" ,
  "Scizor" : "Bug	Steel" ,
  "Scolipede" : "Bug	Poison" ,
  "Scorbunny" : "Fire	" ,
  "Scrafty" : "Dark	Fighting" ,
  "Scraggy" : "Dark	Fighting" ,
  "Scyther" : "Bug	Flying" ,
  "Seadra" : "Water	" ,
  "Seaking" : "Water	" ,
  "Sealeo" :	"Ice	Water" ,
  "Seedot" :	"Grass		" ,
  "Seel" : "Water	" ,
  "Seismitoad" : "Water	Ground" ,
  "Sentret" : "Normal	" ,
  "Serperior" : "Grass	" ,
  "Servine" : "Grass	" ,
  "Seviper" :	"Poison		" ,
  "Sewaddle" : "Bug	Grass" ,
  "Sharpedo" :	"Water	Dark	" ,
  "Shaymin" : "Grass		" ,
  "Shedinja" :	"Bug	Ghost	" ,
  "Shelgon" :	"Dragon	" ,
  "Shellder" : "Water	" ,
  "Shellos" : "Water		" ,
  "Shelmet" : "Bug	" ,
  "Shieldon" : "Rock	Steel	" ,
  "Shiftry" :	"Grass	Dark	" ,
  "Shiinotic" : "Grass	Fairy" ,
  "Shinx" : "Electric		" ,
  "Shroomish" :	"Grass		" ,
  "Shuckle" : "Bug	Rock" ,
  "Shuppet" :	"Ghost	" ,
  "Sigilyph" : "Psychic	Flying" ,
  "Silcoon" :	"Bug		" ,
  "Silicobra" : "Ground	" ,
  "Silvally" : "Normal	" ,
  "Simipour" : "Water	" ,
  "Simisage" : "Grass	" ,
  "Simisear" : "Fire	" ,
  "Sinistea" : "Ghost	" ,
  "Sirfetch'd": 	"Fighting	" ,
  "Sizzlipede" : "Fire	Bug" ,
  "Skarmory" : "Steel	Flying" ,
  "Skiddo" : "Grass	" ,
  "Skiploom" : "Grass	Flying" ,
  "Skitty" :	"Normal		" ,
  "Skorupi" : "Poison	Bug	" ,
  "Skrelp" : "Poison	Water" ,
  "Skuntank" : "Poison	Dark	" ,
  "Skwovet" : "Normal	" ,
  "Slaking" :	"Normal		" ,
  "Slakoth" :	"Normal		" ,
  "Sliggoo" : "Dragon	" ,
  "Slowbro" : "Water	Psychic" ,
  "Slowking" : "Water	Psychic" ,
  "Slowpoke" : "Water	Psychic" ,
  "Slugma" : "Fire	" ,
  "Slurpuff" : "Fairy	" ,
  "Smeargle" : "Normal	" ,
  "Smoochum" : "Ice	Psychic" ,
  "Sneasel" : "Dark	Ice" ,
  "Snivy" : "Grass	" ,
  "Snom" : "Ice	Bug" ,
  "Snorlax" : "Normal	" ,
  "Snorunt" :	"Ice	" ,
  "Snover" : "Grass	Ice	" ,
  "Snubbull" : "Fairy" ,
  "Sobble" : "Water	" ,
  "Solgaleo" : "Psychic	Steel" ,
  "Solosis" : "Psychic	" ,
  "Solrock" :	"Rock	Psychic	" ,
  "Spearow" : "Normal	Flying" ,
  "Spectrier" : "Ghost	" ,
  "Spewpa" : "Bug	" ,
  "Spheal" :	"Ice	Water" ,
  "Spinarak" : "Bug	Poison" ,
  "Spinda" :	"Normal		" ,
  "Spiritomb" : "Ghost	Dark	" ,
  "Spoink" :	"Psychic		" ,
  "Spritzee" : "Fairy	" ,
  "Squirtle" : "Water	" ,
  "Stakataka" : "Rock	Steel" ,
  "Stantler" : "Normal	" ,
  "Staraptor" : "Normal	Flying	" ,
  "Staravia" : "Normal	Flying	" ,
  "Starly" : "Normal	Flying	" ,
  "Starmie" : "Water	Psychic" ,
  "Staryu" : "Water	" ,
  "Steelix" : "Steel	Ground" ,
  "Steenee" : "Grass	" ,
  "Stonjourner" : "Rock	" ,
  "Stoutland" : "Normal	" ,
  "Stufful" : "Normal	Fighting" ,
  "Stunfisk" : "Ground	Electric" ,
  "Stunky" : "Poison	Dark	" ,
  "Sudowoodo" : "Rock	" ,
  "Suicune" : "Water	" ,
  "Sunflora" : "Grass	" ,
  "Sunkern" : "Grass	" ,
  "Surskit" :	"Bug	Water	" ,
  "Swablu" :	"Normal	Flying	" ,
  "Swadloon" : "Bug	Grass" ,
  "Swalot" :	"Poison		" ,
  "Swampert" :	"Water	Ground	" ,
  "Swanna" : "Water	Flying" ,
  "Swellow" :	"Normal	Flying	" ,
  "Swinub" : "Ice	Ground" ,
  "Swirlix" : "Fairy	" ,
  "Swoobat" : "Psychic	Flying" ,
  "Sylveon" : "Fairy	" ,
  "Taillow" :	"Normal	Flying	" ,
  "Talonflame" : "Fire	Flying" ,
  "Tangela" : "Grass	" ,
  "Tangrowth" : "Grass		" ,
  "Tapu Bulu" : 	"Grass	Fairy	" ,
  "Tapu Fini" : 	"Water	Fairy	" ,
  "Tapu Koko" : 	"Electric	Fairy	" ,
  "Tapu Lele" : 	"Psychic	Fairy	" ,
  "Tauros" : "Normal	" ,
  "Teddiursa" : "Normal	" ,
  "Tentacool" : "Water	Poison" ,
  "Tentacruel" : "Water	Poison" ,
  "Tepig" : "Fire	" ,
  "Terrakion" : "Rock	Fighting" ,
  "Thievul" : "Dark	" ,
  "Throh" : "Fighting	" ,
  "Thundurus" : "Electric	Flying" ,
  "Thwackey" : "Grass	" ,
  "Timburr" : "Fighting	" ,
  "Tirtouga" : "Water	Rock" ,
  "Togedemaru" : "Electric	Steel" ,
  "Togekiss" : "Fairy	Flying	" ,
  "Togepi" : "Fairy" ,
  "Togetic" : "Fairy	Flying" ,
  "Torchic" :	"Fire		" ,
  "Torkoal" :	"Fire		" ,
  "Tornadus" : "Flying	" ,
  "Torracat" : "Fire	" ,
  "Torterra" : "Grass	Ground	" ,
  "Totodile" : "Water	" ,
  "Toucannon" : "Normal	Flying" ,
  "Toxapex" : "Poison	Water" ,
  "Toxel" : "Electric	Poison" ,
  "Toxicroak" : "Poison	Fighting	" ,
  "Toxtricity" : "Electric	Poison" ,
  "Tranquill" : "Normal	Flying" ,
  "Trapinch" :	"Ground		" ,
  "Treecko" :	"Grass" ,
  "Trevenant" : "Ghost	Grass" ,
  "Tropius" :	"Grass	Flying" ,
  "Trubbish" : "Poison	" ,
  "Trumbeak" : "Normal	Flying" ,
  "Tsareena" : "Grass	" ,
  "Turtonator" : "Fire	Dragon" ,
  "Turtwig" : "Grass		" ,
  "Tympole" : "Water	" ,
  "Tynamo" : "Electric	" ,
  "Type : Null" : 	"Normal" ,
  "Typhlosion" : "Fire	" ,
  "Tyranitar" : "Rock	Dark" ,
  "Tyrantrum" : "Rock	Dragon" ,
  "Tyrogue" : "Fighting	" ,
  "Tyrunt" : "Rock	Dragon" ,
  "Umbreon" : "Dark	" ,
  "Unfezant" : "Normal	Flying" ,
  "Unown" : "Psychic	" ,
  "Ursaring" : "Normal	" ,
  "Urshifu" : "Fighting	Dark" ,
  "Uxie" : "Psychic		" ,
  "Vanillish" : "Ice	" ,
  "Vanillite" : "Ice	" ,
  "Vanilluxe" : "Ice	" ,
  "Vaporeon" : "Water	" ,
  "Venipede" : "Bug	Poison" ,
  "Venomoth" : "Bug	Poison" ,
  "Venonat" : "Bug	Poison" ,
  "Venusaur" : "Grass	Poison" ,
  "Vespiquen" : "Bug	Flying	" ,
  "Vibrava" :	"Ground	Dragon	" ,
  "Victini" : "Psychic	Fire" ,
  "Victreebel" : "Grass	Poison" ,
  "Vigoroth" :	"Normal		" ,
  "Vikavolt" : "Bug	Electric" ,
  "Vileplume" : "Grass	Poison" ,
  "Virizion" : "Grass	Fighting" ,
  "Vivillon" : "Bug	Flying" ,
  "Volbeat" :	"Bug		" ,
  "Volcanion" : "Fire	Water" ,
  "Volcarona" : "Bug	Fire" ,
  "Voltorb" : "Electric	" ,
  "Vullaby" : "Dark	Flying" ,
  "Vulpix" : "Fire	" ,
  "Wailmer" :	"Water		" ,
  "Wailord" :	"Water		" ,
  "Walrein" :	"Ice	Water" ,
  "Wartortle" : "Water	" ,
  "Watchog" : "Normal	" ,
  "Weavile" : "Dark	Ice	" ,
  "Weedle" : "Bug	Poison" ,
  "Weepinbell" : "Grass	Poison" ,
  "Weezing" : "Poison	" ,
  "Whimsicott" : "Grass	Fairy" ,
  "Whirlipede" : "Bug	Poison" ,
  "Whiscash" :	"Water	Ground	" ,
  "Whismur" :	"Normal		" ,
  "Wigglytuff" : "Normal	Fairy" ,
  "Wimpod" : "Bug	Water" ,
  "Wingull" :	"Water	Flying	" ,
  "Wishiwashi" : "Water	" ,
  "Wobbuffet" : "Psychic	" ,
  "Woobat" : "Psychic	Flying" ,
  "Wooloo" : "Normal	" ,
  "Wooper" : "Water	Ground" ,
  "Wormadam" : "Bug	Grass" ,
  "Wurmple" :	"Bug		" ,
  "Wynaut" :	"Psychic	" ,
  "Wyrdeer" : "Normal	Psychic" ,
  "Xatu" : "Psychic	Flying" ,
  "Xerneas" : "Fairy	" ,
  "Xurkitree" : "Electric	" ,
  "Yamask" : "Ghost	" ,
  "Yamper" : "Electric	" ,
  "Yanma" : "Bug	Flying" ,
  "Yanmega" : "Bug	Flying	" ,
  "Yungoos" : "Normal	" ,
  "Yveltal" : "Dark	Flying" ,
  "Zacian" : "Fairy	Steel" ,
  "Zamazenta" : "Fighting	Steel" ,
  "Zangoose" :	"Normal		" ,
  "Zapdos" : "Electric	Flying" ,
  "Zarude" : "Dark	Grass" ,
  "Zebstrika" : "Electric	" ,
  "Zekrom" : "Dragon	Electric" ,
  "Zeraora" : "Electric	" ,
  "Zigzagoon" :	"Normal		" ,
  "Zoroark" : "Dark	" ,
  "Zorua" : "Dark	" ,
  "Zubat" : "Poison	Flying" ,
  "Zweilous" : "Dark	Dragon" ,
  "Zygarde" : "Dragon	Ground"
  };
const pokemonName = Object.keys(pokeDb);

function App() {
  // define useState and functions
  var [pokeType, setPokemonType] = useState("");
  var [pokeName, setPokemonName] = useState("");

  // function to show type on click
  function clickPokemonTypeHandler(pokemon){
    pokeType = pokeDb[pokemon];
    setPokemonType(pokeType);
    setPokemonName(pokemon);
  }


  return (
    <div className="App">

      {/* heading msgs */}
      <h1 className="pokemon">{headingText}</h1>
      <h2 className = "heading">{descMsg1}</h2>
      <h2 className = "heading">{descMsg2}</h2>

    {/* pokemon name */}
    <h2 className="heading op">PoKeMoN NaMe</h2>
    <div className = "pokemon-name"> {pokeName} </div>

    {/* pokemon type */}
      <h2 className = "heading op">PoKeMoN TyPe HeRe 👇</h2>
      <div className = "pokemon-type"> {pokeType} </div>
      
      {/* pokemon list  and callback functions*/}
      <h2 className="heading-pokemon">PoKeMoNs We KnOw</h2>
      <span className="heading-emoji">👇</span>
      <div className="poke-box scroll-bar">{pokemonName.map(function(pokemon){
        return (
        <span className="poke-name" key={pokemon} onClick={() => clickPokemonTypeHandler(pokemon)}> 
        {pokemon} 
        </span>)
      })}</div>

    </div>
  );
}

export default App;
